# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5B_7R67O9y1N4Y7opSdRT2Vfv-OeTd6
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

df = pd.read_csv("/content/covid_19_clean_complete.csv")

df.rename(columns={
    'Province/State': 'Province',
    'Country/Region': 'Country',
    'Date': 'Date'
}, inplace=True)

df['Date'] = pd.to_datetime(df['Date'])
df['Province'] = df['Province'].fillna("N/A")
df.fillna(0, inplace=True)

df['Active'] = df['Confirmed'] - df['Deaths'] - df['Recovered']
latest_date = df['Date'].max()

top_countries = df[df['Date'] == latest_date] \
    .groupby('Country')['Confirmed'].sum() \
    .sort_values(ascending=False).head(15).index.tolist()

df_top = df[df['Country'].isin(top_countries)]
df_grouped = df_top.groupby(['Country', 'Date'])[['Confirmed', 'Deaths', 'Recovered', 'Active']].sum().reset_index()

kpi_summary = df_grouped[df_grouped['Date'] == latest_date].groupby('Country')[['Confirmed', 'Deaths', 'Recovered', 'Active']].sum()
display(kpi_summary)

plt.figure(figsize=(8, 6))
sns.heatmap(kpi_summary.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap - COVID-19 KPIs")
plt.tight_layout()
plt.show()

plt.figure(figsize=(14, 7))
for country in top_countries:
    country_data = df_grouped[df_grouped['Country'] == country]
    plt.plot(country_data['Date'], country_data['Confirmed'], label=country)

plt.title("Confirmed Cases Over Time - Top 15 Countries")
plt.xlabel("Date")
plt.ylabel("Confirmed Cases")
plt.legend(loc='upper left', fontsize='small')
plt.tight_layout()
plt.show()